package org.ya.green.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.ya.green.db.Company;
import org.ya.green.db.Staff;

import org.ya.green.db.CompanyDao;
import org.ya.green.db.StaffDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig companyDaoConfig;
    private final DaoConfig staffDaoConfig;

    private final CompanyDao companyDao;
    private final StaffDao staffDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        companyDaoConfig = daoConfigMap.get(CompanyDao.class).clone();
        companyDaoConfig.initIdentityScope(type);

        staffDaoConfig = daoConfigMap.get(StaffDao.class).clone();
        staffDaoConfig.initIdentityScope(type);

        companyDao = new CompanyDao(companyDaoConfig, this);
        staffDao = new StaffDao(staffDaoConfig, this);

        registerDao(Company.class, companyDao);
        registerDao(Staff.class, staffDao);
    }
    
    public void clear() {
        companyDaoConfig.getIdentityScope().clear();
        staffDaoConfig.getIdentityScope().clear();
    }

    public CompanyDao getCompanyDao() {
        return companyDao;
    }

    public StaffDao getStaffDao() {
        return staffDao;
    }

}
